[project]
name = "promptlibz"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "pytest>=8.3.5",
    "pytest-html>=4.1.1",
]
